version: "3.8"

services:
  server:
    build:
      context: cmd/server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080

  client:
    build:
      context: cmd/client
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - server