version: "3.8"

services:
  server:
    image: ghcr.io/<your_github_username>/webasm-latency-server:latest
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080

  client:
    image: ghcr.io/korjavin/webasm-latency-client:latest
    ports:
      - "80:80"
    environment:
      SERVER_HOST: server
      SERVER_PORT: 8080
    depends_on:
      - server